### ISSUE TITLE
Cant connect to arduino uno

### ISSUE THREAD

**Issue by dugs1212** [mic159/octoprint-grbl-plugin#1]
I can not for the life of me get this to connect to an arduino uno for an xcarve. Any advise would be greatly appreciated. 

I have downloaded the plug in and I can start the connection process but it never fully connects.

**Comment by mic159** [comment]
@dugs1212 what version of GRBL are you using?
And can you paste what's in the terminal output tab?

**Comment by mic159** [comment]
I think I fixed the issue!
Try the new version: https://github.com/mic159/octoprint-grbl-plugin/releases/tag/1.0.1

I have a PR to update it in the octoprint plugin manager: https://github.com/OctoPrint/plugins.octoprint.org/pull/83

Re-open this issue if its not fixed
